260926

diff --git a/document/code/diagrams/creatediagram b/document/code/diagrams/creatediagram
--- a/document/code/diagrams/creatediagram
+++ b/document/code/diagrams/creatediagram
@@ -14,19 +14,19 @@ chkdep() {
   then
     return 0
   else
-    echo -e "\nERROR: The '$1' is required to use the script."
+    echo -e "\nERROR: The '${1}' is required to use the script."
     return 127
   fi
 }
 
 # check dependency
-chkdep plantuml; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
+chkdep plantuml; TOBE=$?; if [ $TOBE -ne 0 ]; then exit; fi
 # make diagrams
 for file in source/*.puml; do
   if [ -f "$file" ]; then
     y=$(basename "$file" .puml)
     for x in $FORMAT; do
-      echo "$y.puml -> .$x"
+      echo "${y}.puml -> .${x}"
       plantuml -t"$x" -o"../" "$file"
     done
   fi
diff --git a/help/md2html b/help/md2html
--- a/help/md2html
+++ b/help/md2html
@@ -14,13 +14,13 @@ chkdep() {
   then
     return 0
   else
-    echo -e "\nERROR: The '$1' is required to use the script."
+    echo -e "\nERROR: The '${1}' is required to use the script."
     return 127
   fi
 }
 
 # check dependency
-chkdep pandoc; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
+chkdep pandoc; TOBE=$?; if [ $TOBE -ne 0 ]; then exit; fi
 # convert files
 for x in $FILES
 do
diff --git a/project/bin2hex b/project/bin2hex
--- a/project/bin2hex
+++ b/project/bin2hex
@@ -12,12 +12,12 @@ chkdep() {
   then
     return 0
   else
-    echo -e "\nERROR: The '$1' is required to use the script."
+    echo -e "\nERROR: The '${1}' is required to use the script."
     return 127
   fi
 }
 
 # check dependency
-chkdep objcopy; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
+chkdep objcopy; TOBE=$?; if [ $TOBE -ne 0 ]; then exit; fi
 # convert file
-objcopy -I binary -O ihex $1 $1.bin
+objcopy -I binary -O ihex "$1" "${1}.bin"
diff --git a/syntax/createvsix b/syntax/createvsix
--- a/syntax/createvsix
+++ b/syntax/createvsix
@@ -12,13 +12,13 @@ chkdep() {
   then
     return 0
   else
-    echo -e "\nERROR: The '$1' is required to use the script."
+    echo -e "\nERROR: The '${1}' is required to use the script."
     return 127
   fi
 }
 
 # check dependency
-chkdep vsce; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
+chkdep vsce; TOBE=$?; if [ $TOBE -ne 0 ]; then exit; fi
 # create .vsix file
 cd corelab-scriptembly
 vsce package
