260926

diff --git a/document/code/diagrams/creatediagram b/document/code/diagrams/creatediagram
--- a/document/code/diagrams/creatediagram
+++ b/document/code/diagrams/creatediagram
@@ -6,21 +6,31 @@
 # | Create UML diagram picture                                                 |
 # +----------------------------------------------------------------------------+
 
-format='pdf'
+FORMAT='pdf'
 
-if command -v plantuml >/dev/null 2>&1; then
-  for file in source/*.puml; do
-    if [ -f "$file" ]; then
-      y=$(basename "$file" .puml)
-      for x in $format; do
-        echo "$y.puml -> .$x"
-        plantuml -t"$x" -o"../" "$file"
-      done
-    fi
-  done
-else
-  echo "ERROR: The PlantUML is not installed."
-fi
+# CHECK DEPENDENCY
+chkdep() {
+  if command -v $1 >/dev/null 2>&1;
+  then
+    return 0
+  else
+    echo -e "\nERROR: The '$1' is required to use the script."
+    return 127
+  fi
+}
+
+# check dependency
+chkdep plantuml; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
+# make diagrams
+for file in source/*.puml; do
+  if [ -f "$file" ]; then
+    y=$(basename "$file" .puml)
+    for x in $FORMAT; do
+      echo "$y.puml -> .$x"
+      plantuml -t"$x" -o"../" "$file"
+    done
+  fi
+done
 
 # If the output PDF is too large, use Ghostscript to reduce the size:
 #
diff --git a/help/md2html b/help/md2html
--- a/help/md2html
+++ b/help/md2html
@@ -1,9 +1,28 @@
 #!/bin/bash
-# convert .md files to .html
+# +----------------------------------------------------------------------------+
+# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
+# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
+# | md2html                                                                    |
+# | .md to .html converter                                                     |
+# +----------------------------------------------------------------------------+
 
-files=`ls *.md`
+FILES=`ls *.md`
 
-for x in $files
+# CHECK DEPENDENCY
+chkdep() {
+  if command -v $1 >/dev/null 2>&1;
+  then
+    return 0
+  else
+    echo -e "\nERROR: The '$1' is required to use the script."
+    return 127
+  fi
+}
+
+# check dependency
+chkdep pandoc; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
+# convert files
+for x in $FILES
 do
   echo $x
   cat $x | grep -v '\# Core' | grep -v '\*\*Modular' | grep -v 'Copy' > temp.tmp
diff --git a/project/hex2bin b/project/hex2bin
--- a/project/hex2bin
+++ b/project/hex2bin
@@ -1,4 +1,23 @@
 #!/bin/bash
-# convert Intel hexa files to raw binary
+# +----------------------------------------------------------------------------+
+# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
+# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
+# | hex2bin                                                                    |
+# | Convert Intel hexa file to binary                                          |
+# +----------------------------------------------------------------------------+
 
+# CHECK DEPENDENCY
+chkdep() {
+  if command -v $1 >/dev/null 2>&1;
+  then
+    return 0
+  else
+    echo -e "\nERROR: The '$1' is required to use the script."
+    return 127
+  fi
+}
+
+# check dependency
+chkdep objcopy; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
+# convert file
 objcopy -I ihex -O binary $1 $1.bin
diff --git a/syntax/createvsix b/syntax/createvsix
--- a/syntax/createvsix
+++ b/syntax/createvsix
@@ -1,7 +1,25 @@
 #!/bin/bash
+# +----------------------------------------------------------------------------+
+# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
+# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
+# | createvsix                                                                 |
+# | Create .vsix file                                                          |
+# +----------------------------------------------------------------------------+
 
-# Create .vsix file
+# CHECK DEPENDENCY
+chkdep() {
+  if command -v $1 >/dev/null 2>&1;
+  then
+    return 0
+  else
+    echo -e "\nERROR: The '$1' is required to use the script."
+    return 127
+  fi
+}
 
+# check dependency
+chkdep vsce; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
+# create .vsix file
 cd corelab-scriptembly
 vsce package
 mv *.vsix ..
